### ISSUE TITLE
Missing xcassets

### ISSUE THREAD

**Issue by ideologysec** [jonjon1251/TheLaughingMan-ARKit#2]
Hello, this app looks like great fun!

I've compiled it successfully, but it's missing the xcassets folder. Would you be willing to add those to the repo so buttons and the image overlay work properly?

Thanks!

**Comment by jonjon1251** [comment]
Hey there sorry about that I will try to upload it as soon as I can

**Comment by jonjon1251** [comment]
It should be fixed now let me know if its working for you
